### PR TITLE
Created Promisify shim

### PR DESCRIPTION
**Pull request by mboperator**
## Why
Shimming `promisify` because it's only available in Node v8.4.0+
Also did some linting.

cc @mcclayton @ben-burlingham

### CODE REVIEW

**Comment by mcclayton** [comment]
Thanks @mboperator 🚀

**Comment by mcclayton** [comment]
Note: You can remove step 0 from https://github.com/procore/particles#how-do-i-get-started

**Comment by ben-burlingham** [comment]
Rather than requiring our users (who may not be engineers) to all debug and upgrade their node installations, is there a more backwards-compatible solution we could use?

Either, write vanilla promises, or use an existing NPM package, or...lots of options here that don't block people.

**Comment by mboperator** [comment]
@ben-burlingham This is the backwards compatible solution, if users are using a Node version prior to 8.0 the script will utilize the shim.

**Comment by ben-burlingham** [comment]
Still confused why we need all these updates to support vanilla functionality.

**Comment by ben-burlingham** [comment]
OK reading thanks!

**Pull request merged**
