### PR TITLE
[Table] Fix minor table resize issues in Horizontal Slider

### PR DESCRIPTION
**Pull request by scottwalstead**
### Summary
There was a timing issue for the Directory Table where the width of the table wasn't being measured correctly because it was being measured too early in HorizontalScroller's componentDidMount

Running onResize when the browser triggers a window onload event fixes that timing issue for us

Also fixes onResize pointing to a non existent function (this.reset)

### CODE REVIEW

**Comment by ben-burlingham** [comment]
...pending conflicts

**Comment by nick-morrill** [comment]
@scottwalstead I think you may have added me as a reviewer by mistake 😜

**Comment by scottwalstead** [comment]
@nick-morrill yeah. my bad. Added the wrong Nick.

**Comment by scottwalstead** [comment]
@ben-burlingham just resolved them

**Pull request merged**
